# Generated by Django 2.0.2 on 2018-02-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MedClerkPreSed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinician', models.CharField(max_length=200)),
                ('current_health_status', models.TextField(blank=True, help_text='Please Comment on URTI/Seizures/Flu/Bladder Incontinence/LRTI/Swallowing Difficulty')),
                ('met', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'n/a')], default='no', max_length=3)),
                ('met_time', models.DateTimeField()),
                ('record_medication_changes', models.TextField(blank=True, help_text='Record Medication Changes Since Pre-Injection Assessment')),
                ('respiratory_examination_details', models.TextField(blank=True, help_text='Respiratory Examination Details')),
                ('normal', models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('na', 'n/a')], default='na', max_length=8)),
                ('fit_for_sedation', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('oral_sedation_time', models.DateTimeField()),
                ('number_of_ametop_tubes_used', models.PositiveSmallIntegerField(default=0)),
                ('ametop_applied_time', models.DateTimeField()),
                ('reasons_for_cancellation', models.TextField(blank=True, help_text='If Applicable, State Reasons for Cancellation')),
                ('follow_up_arrangements', models.TextField(blank=True, help_text='Outline Follow Up Arrangements Below')),
            ],
        ),
        migrations.CreateModel(
            name='NumberAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_input', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('page', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='form.Page')),
            ],
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Question')),
            ],
        ),
        migrations.AddField(
            model_name='numberanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Question'),
        ),
        migrations.AddField(
            model_name='medclerkpresed',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='form.Patient'),
        ),
    ]
