# Generated by Django 2.0.2 on 2018-03-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20180301_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcOfTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_by', models.CharField(help_text='Initials', max_length=5)),
                ('date', models.DateTimeField()),
                ('last_injection', models.DateTimeField()),
                ('summary_and_effectiveness_of_injection', models.TextField(blank=True, help_text='Summary of Injection Results')),
                ('future_treatment_plan', models.TextField(blank=True, help_text='Details of Future Treatment Plan')),
                ('reinjection', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('if_reinjection_yes', models.TextField(blank=True, help_text='Reason for Re-injection')),
                ('timeframe', models.DateTimeField()),
                ('admin_informed', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('if_reinjection_no', models.TextField(blank=True, help_text='Reason Re-injection Not Indicated')),
                ('onward_referral_plan', models.TextField(blank=True)),
                ('patient', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='form.Patient')),
            ],
        ),
    ]
