# Generated by Django 2.0.2 on 2018-03-02 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20180302_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='procreport',
            name='adverse_event',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('', 'n/a')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='procreport',
            name='adverse_event_yes',
            field=models.TextField(blank=True, help_text='If yes, then details of adverse event'),
        ),
        migrations.AddField(
            model_name='procreport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procreport',
            name='sedation_effective',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('', 'n/a')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='procreport',
            name='sedation_effective_no',
            field=models.TextField(blank=True, help_text='If no, then details of ineffective sedation'),
        ),
    ]
