# Generated by Django 2.0.2 on 2018-02-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20180226_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedClerkPreSed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinician', models.CharField(max_length=200)),
                ('current_health_status', models.TextField(help_text='Please Comment on URTI/Seizures/Flu/Bladder Incontinence/LRTI/Swallowing Difficulty')),
                ('met', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'n/a')], default='no', max_length=3)),
                ('met_time', models.DateTimeField()),
                ('record_medication_changes', models.TextField(help_text='Record Medication Changes Since Pre-Injection Assessment')),
                ('respiratory_examination_details', models.TextField(help_text='Respiratory Examination Details')),
                ('normal', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('na', 'n/a')], default='na', max_length=8)),
                ('fit_for_sedation', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('oral_sedation_time', models.DateTimeField()),
                ('number_of_ametop_tubes_used', models.PositiveSmallIntegerField()),
                ('ametop_applied_time', models.DateTimeField()),
                ('reasons_for_cancellation', models.TextField(help_text='If Applicable, State Reasons for Cancellation')),
                ('follow_up_arrangements', models.TextField(help_text='Outline Follow Up Arrangements Below')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
